title: My Blog
author: Helen
description: > # this means to ignore newlines until "baseurl:"
  My blog about my developer projects.

# social links
twitter_username: helenking029
github_username:  helenking029

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minima
